parameters:
  displayName: ''
  workingDirectory: ''

jobs:
  - job: ${{ parameters.displayName }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-latest'

    # variables:
    #   - group: AgoraKeys

    steps:    
      - script: cd ${{ parameters.workingDirectory }} && npm install

      - script: cd ${{ parameters.workingDirectory }} && npm run package:mac

      - script: cd ${{ parameters.workingDirectory }} && zip -r agora-electron-api-example-mac.zip out/Electron\ API\ Demos-darwin-x64

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/agora-electron-api-example-mac.zip
          ArtifactName: ${{ parameters.displayName }}