parameters:
  displayName: ''
  workingDirectory: ''

jobs:
  - job: ${{ parameters.displayName }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    # variables:
    #   - group: AgoraKeys

    steps:    
      - script: cd ${{ parameters.workingDirectory }} && npm install
      
      - script: cd ${{ parameters.workingDirectory }} && npm run write-config
        env:
          AGORA_APP_ID: $(agora.appId)

      - script: cd ${{ parameters.workingDirectory }} && npm run package:win && ls -alt out

      - script: cd ${{ parameters.workingDirectory }} && 7z a -r -tzip agora-electron-api-example-win.zip out/Electron\ API\ Demos-win32-ia32

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/agora-electron-api-example-win.zip
          ArtifactName: ${{ parameters.displayName }}