parameters:
  displayName: ''
  workingDirectory: ''

jobs:
  - job: ${{ parameters.displayName }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'vs2017-win2016'

    # variables:
    #   - group: AgoraKeys

    steps:    
      - script: cd ${{ parameters.workingDirectory }} && npm install

      - script: cd ${{ parameters.workingDirectory }} && npm run dist

      - script: cd ${{ parameters.workingDirectory }} && 7z a -r -tzip agora-electron-premium-win.zip dist/win-ia32-unpacked

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/agora-electron-premium-win.zip
          ArtifactName: ${{ parameters.displayName }}