parameters:
  displayName: ''
  workingDirectory: ''

jobs:
  - job: ${{ parameters.displayName }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-latest'

    # variables:
    #   - group: AgoraKeys

    steps:    
      - script: cd ${{ parameters.workingDirectory }} && npm install
      
      - script: cd ${{ parameters.workingDirectory }} && npm run write-config
        env:
          AGORA_APP_ID: $(agora.appId)

      - script: cd ${{ parameters.workingDirectory }} && npm run dist

      - script: cd ${{ parameters.workingDirectory }} && zip -r agora-electron-premium-mac.zip dist/mac/electron-webpack-quick-start.app

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/agora-electron-premium-mac.zip
          ArtifactName: ${{ parameters.displayName }}